### Registro do usuário
POST https://healthy-mind.onrender.com/register HTTP/1.1
Content-Type: application/json

{
    "nome": "Acsa",
    "telefone": "9874589",
    "genero": "feminino",
    "aniversario": "2005-12-15",
    "email": "acsa_silveira@yahoo.com.br",
    "password": "123456"
}

### Autenticação do usuário
POST https://healthy-mind.onrender.com/login HTTP/1.1
Content-Type: application/json

{
    "email": "acsa_silveira@yahoo.com.br",
    "password": "123456"
}